extends:
  - './node_modules/mobify-code-style/es6/mobify-es6-react.yml'
  - 'plugin:ava/recommended'
plugins:
  - ava
settings:
  import/resolver:
    webpack:
      config: './webpack/base.main.js'
  import/extensions: ['.js', '.jsx']
rules:
  react/react-in-jsx-scope: error
