extends:
  - './node_modules/mobify-code-style/es6/mobify-es6-react.yml'
env:
  node: true
  jest: true
settings:
  import/resolver:
    webpack:
      config: './webpack/base.main.js'
rules:
  react/react-in-jsx-scope: error
