extends:
  - './node_modules/mobify-code-style/es6/mobify-es6-react.yml'
  - 'plugin:ava/recommended'
plugins:
  - ava
rules:
  no-unused-vars:
    - error
    - argsIgnorePattern:
        - '^props$'
        - '^dispatch$'
        - '^state$'
